[package]
name = "proc-macro3"
version = "0.1.0"
edition = "2021"
author = "radiish"

[dependencies]
# *do not* enable the proc-macro2 feature in a proc-macro context
proc-macro2 = { optional = true, version = "^1.0" }

[features]
span-locations = ["proc-macro2/span-locations"]